/*=============================================================================
        FroxelBuild.usf - Build froxel grid
=============================================================================*/
#define FROXEL_DEFINE_UAV 1
#include "FroxelCommon.ush"

RWStructuredBuffer<uint> FroxelGrid;

[numthreads(8,8,8)]
void MainCS(uint3 DTid : SV_DispatchThreadID) {
    // Bounds check

    uint idx = FroxelIndex(DTid);

    FroxelGrid[idx] = idx;
}