#include "/Engine/Private/Common.ush"

RWStructuredBuffer<uint> OutData;

cbuffer FroxelClearCB
{
    uint OutputWidth;
    uint OutputHeight;
    uint _Pad0;
    uint _Pad1;
};

[numthreads(8,8,1)]
void MainCS(uint3 DTid : SV_DispatchThreadID)
{
    if (DTid.x >= OutputWidth || DTid.y >= OutputHeight) return;
    const uint idx = DTid.x + DTid.y * OutputWidth;
    OutData[idx] = DTid.x + DTid.y;
}