/*=============================================================================
        FroxelVisualize.usf - Visualize froxel grid
=============================================================================*/
#include "FroxelCommon.ush"
RWTexture2D<uint> OutTex;

[numthreads(8,8,1)]
void MainCS(uint3 DTid : SV_DispatchThreadID) {
    uint2 pix = DTid.xy;

    uint idx = FroxelIndexFromPix(pix, 0);
    float3 overlay = DebugColorFromIndex(idx);
    OutTex[pix] = float4(overlay, 1.0);
}